ccnmtl/plexus

plexus/s3utils.py
See:
https://github.com/ccnmtl/pump/commit/7dd8fcfb696548f7afd0f257e7efbef1e1a3db1a
=> Normalize timezone to UTC for S3

plexus/main/models.py
set some choices instead of having a free-form text field
=> make edit alias status simpler

plexus/templates/base.html, plexus/templates/main/index.html
make it a bit easier to get to the sections on the main page
=> add simple index menu

media/js/smoketests.js
Fixes error:
Uncaught TypeError: Cannot read property 'split' of undefined
=> Fix js error in smoketests.js

plexus/templates/admin/login.html
=> Fix admin local login

django.mk
for other projects mostly, but the idea is to standardize the .mk files
=> flake8 rule needs to support more than the app dir

plexus/main/migrations/0003_auto_20151210_0424.py
=> add missing migration

requirements.txt
Using development version of django-compressor, to see if it's working
in Django 1.9.
=> Django 1.9

plexus/main/views.py
incorrect indentation. if you add a server without an IP address, it
wouldn't add the contact.
=> fix bug with adding contact to server

plexus/main/tests/test_views.py, plexus/main/views.py, plexus/templates/main/alias_detail.html
make request alias change work like request new alias. User must select
which IP they want the alias to point to.
=> request alias change bugfix. PMT #104543

plexus/templates/main/server_detail.html
I ran whitespace-cleanup-region on this file, and fixed some of the
bootstrap formatting in the request/add alias forms, adding div
separators where appropriate and bootstrap classes.
=> Request alias form cleanup

plexus/templates/main/server_detail.html
=> remove domU form

plexus/main/tests/test_views.py, plexus/main/views.py, plexus/templates/main/alias_detail.html, plexus/urls.py
for internal housekeeping. just change the alias entry in plexus,
without actually sending an email to hostmaster.
=> simple change alias form

requirements.txt
=> remove dependency on urllib3

requirements.txt
not used yet. setting up for a test of a config for our django apps
sending email via SES.
=> add django-smtp-ssl

Dockerfile, README.md, docker-compose.yml, docker-run.sh, plexus/settings_docker.py
run the full `make` when building the docker image.
Also updated the docker-compose setup and documented how that all works.
=> update docker/docker-compose setup

plexus/main/models.py, plexus/templates/main/contact_detail.html
contact page shouldn't show deprecated servers/applications.
=> Hide deprecated servers on contact page

plexus/templates/500.html
Sentry now supports collecting feedback:
* https://docs.sentry.io/hosted/learn/user-feedback/
* https://docs.sentry.io/hosted/clients/python/integrations/django/#python-django-user-feedback
=> collect user feedback in sentry on 500 errors

requirements.txt
required also installing djangorestframework
=> :arrow_up: wagtail 1.7

media/css/portfolio.css, plexus/templates/portfolio/entry.html, plexus/templates/portfolio/entry_index.html
=> Theming experimentation

plexus/portfolio/views.py, plexus/templates/portfolio/entry_index.html, plexus/templates/portfolio/search_results.html, plexus/urls.py
no filtering or anything, just a basic search.
Should default to the database backend if not connected to elasticsearch.
=> super basic search interface for project portfolio

plexus/templates/main/add_application.html, plexus/templates/main/add_server.html, plexus/templates/main/application_detail.html
mostly missing some `form-control` classes
=> clean up some bootstrap forms

plexus/main/models.py, plexus/main/tests/test_models.py, plexus/main/tests/test_views.py, plexus/main/views.py, plexus/templates/main/application_detail.html, plexus/urls.py
haven't changed the actual model class/db table, since that would
require a migration, but at least now all the visible parts are consistent.
=> rename lease to renewal

.dockerignore, .gitignore, docker-compose.yml, plexus/settings_compose.py, plexus/settings_docker.py, plexus/settings_shared.py, requirements.txt
no tasks yet, but I'm planning on switching the email sending to celery
and I want to set up beat to check for expiring renewals periodically.
=> add celery

requirements.txt
with that last wagtail update, 1.11 is now feasible.
=> :arrow_up: Django 1.11

plexus/templates/main/index.html
and make both button links more visible
=> Move Add Server button to top of table

.gitignore
Please leave this open for a bit. i want to see when/if Codacy kicks in.
=> trivial change to test codacy

plexus/grainlog/tests/test_views.py, plexus/grainlog/views.py
=> Make grainlogs/raw public again

plexus/grainlog/tests/test_views.py, plexus/grainlog/urls.py, plexus/grainlog/views.py
lock down functionality that isn't required for internal utilities
=> add login requirements

plexus/main/admin.py
I made a note that I need to edit because it's showing up wrong with
markdown.
=> Add Note to plexus admin

plexus/grainlog/tests/test_views.py, plexus/grainlog/views.py, plexus/main/migrations/0001_initial.py, plexus/main/migrations/0002_auto_20141219_1407.py, plexus/main/migrations/0003_auto_20151210_0424.py, plexus/main/models.py, plexus/main/tests/test_views.py, plexus/main/views.py, plexus/urls.py, requirements.txt
This reverts commit 54d1b15103e50db05f955fb3644c919843e2ca7f.
=> Revert ":arrow_up: django 2.2.3"

plexus/grainlog/admin.py
Should simplify things if we run into problems again.
=> Add GrainLog model to admin

.travis.yml, requirements.txt
See: https://github.com/ccnmtl/ctldjango/pull/257
=> Use astroid instead of logilab, test on ubuntu 18

plexus/settings_shared.py, plexus/templates/main/application_detail.html, requirements.txt
Also, remove feedparser along the way.
=> Remove PMT data from application detail page

plexus/templates/admin/login.html, requirements.txt
=> Upgrade django3.2

requirements.txt
=> Revert "Bump asgiref from 3.4.1 to 3.5.0"

plexus/main/views.py, plexus/templates/main/add_server.html
This info is accessible dynamically via salt - no need for manual input
here.
Also fixed a bunch of bootstrap form issues here.
=> Remove disk and swap from Add Server form

requirements.txt
=> Revert "⬆️ Bump cryptography from 39.0.1 to 40.0.0"

plexus/settings_production.py, plexus/settings_staging.py
https://github.com/getsentry/sentry-python/issues/877#issuecomment-1662588242
=> Add sentry collectstatic fix

plexus/settings_production.py, plexus/settings_staging.py
* ignore sentry during migrate
=> sentry jenkins fix
