requirements.txt
I didn't run the tests locally, but I'm glad jenkins caught this: http://jenkins.ccnmtl.columbia.edu/job/plexus-staging/85/console
=> Add python-dateutil for UTC S3 fix

plexus/settings_production.py, plexus/settings_staging.py
Played around with Cloudfront this weekend and realized that it's fairly trivial to convert our stuff over to use cloudfront instead of serving direct from S3. Latency is definitely lower (especially from Europe), and it's actually a bit cheaper.
In the AWS console, you just go into Cloudfront and create a new distribution, using one of our S3 static buckets as the origin. Everything else can be left as default. It takes 15-20 minutes for it to be fully setup (DNS propagation). Then, just take note of the random domain it generated, and put it into the `AWS_S3_CUSTOM_DOMAIN` settings and tweak the URLs.
=> use Cloudfront for serving static files

plexus/templates/main/application_detail.html, plexus/templates/main/application_graphs.html, plexus/templates/main/graphite_graph.html, plexus/templates/main/server_detail.html, plexus/templates/main/server_graphs.html
The realtime cubism.js stuff is neat and looks impressive, but after living with it for a while now, I'm feeling like I really prefer the simpler plain old static graphite image graphs when it comes to actually seeing anomalies and trends quickly.
This converts the graphs on the server detail page. I'll do application graphs in a bit.
=> convert server graphs from cubism.js to plain graphite image graphs

plexus/templates/base.html
Sorry, I messed this up. We need the `/` here when not on the main page.
=> Add back root path to nav options

requirements.txt
It doesn't look like plexus is using this
=> Remove django-indexer

plexus/grainlog/models.py, plexus/grainlog/tests/factories.py, plexus/grainlog/tests/test_models.py, plexus/grainlog/tests/test_views.py, plexus/grainlog/urls.py, plexus/grainlog/views.py, plexus/settings_shared.py, plexus/templates/base.html, plexus/templates/grainlog/grainlog_detail.html, plexus/templates/grainlog/grainlog_list.html, plexus/urls.py, test_data/grains.json
a simple view that a script on the salt master can POST grains.json files to, plus a few very basic ones for viewing them.
Right now it's wide open. I want to get the basics working before thinking too much about what sort of auth we'll want (if any).
=> Add Grainlog endpoint

plexus/grainlog/grain.py, plexus/grainlog/models.py, plexus/grainlog/tests/test_grain.py, plexus/templates/grainlog/grainlog_detail.html
beginning to parse the data out of the big json dump and slice and dice
it in more useful ways.
The grain detail page now shows breakdowns by server, by app, by proxy,
and by role. Still ugly, but I think it's more clear where I'm going
with this.
=> grain parsing and display

plexus/grainlog/grain.py, plexus/grainlog/tests/test_grain.py
See:
https://sentry.ccnmtl.columbia.edu/sentry-internal/plexus/group/1005/
Sometimes, when salt can't talk to a server, instead of a dict of grain
data for the server, we instead get the string "Minion did not return. [Not
Connected]".
Deal with this by avoiding trying to load any server data that doesn't
look like a valid dict.
=> fix bug with invalid server data

plexus/main/models.py, plexus/main/views.py, plexus/templates/main/index.html
The index page on Plexus has a lot of data there now and is starting to get a bit pokey.
Did some `.select_related()`s here and there and got it down from 920 queries and about 6s on my desktop down to 254 queries and 2s.
That's pretty much just the low hanging fruit. Almost everything that's left is the retrieving of the list of contacts for each application/alias/server. That will be a little trickier to eliminate.
=> Index speedup

plexus/main/views.py
it was using the `ApplicationContact` or `ServerContact` id rather than
the `Server` or `Application` id.
=> fix redirect on application/server contact delete

plexus/main/views.py
Based on:
https://github.com/ccnmtl/dmt/commit/270774faf4cfc4f1f7735b9be76002f86d14c4c1
Addresses sentry error:
https://sentry.ccnmtl.columbia.edu/sentry-internal/plexus/group/1138/
=> Fix 500 error - email rejection when requesting alias

requirements.txt
everywhere else we use 'django-compressor' instead of 'django_compressor'
=> fix django-compressor requirement

plexus/templates/main/server_detail.html
we aren't tracking contacts for aliases anymore
=> remove contacts column from aliases table on server detail page

docker-compose.yml, plexus/portfolio/models.py, plexus/settings_compose.py, requirements.txt
when running locally with docker-compose, it now uses elasticsearch as
the search backend.
Assuming you have docker-compose installed properly, you should be able
to check this out on a fresh system and do:
$ docker-compose run web migrate # to set up database schema
$ docker-compose run web manage update_index # to create the es indices
$ docker-compose up
and it should be running on port 8000, ready to login and start adding content.
=> elasticsearch integration for compose

requirements.txt
the wagtail elasticsearch backend depends on it (despite not requiring
it at install time)
=> add urllib3

plexus/templates/main/application_detail.html
leftover from before. smoketests are shown in the graphs section now.
=> remove extraneous smoketest section

docker-compose.yml
this will require docker-compose of at least version 1.6.0
https://github.com/docker/compose/blob/master/CHANGELOG.md#160-2016-01-15
which introduces the `services` section, which has a nice feature of
letting you specify the dependencies between services so, eg, the django
container won't start until after the db and elasticsearch containers.
If you get:
```docker-compose up
Unsupported config option for services service: 'db'
```
that means you have an old version of docker-compose and need to update.
=> update to newer docker-compose syntax

plexus/main/models.py, plexus/main/tests/factories.py, plexus/main/tests/test_models.py, plexus/main/tests/test_views.py, plexus/main/views.py, plexus/templates/main/application_detail.html, plexus/urls.py
This is clearly just some early stage work so we can get started, but it
lets us add a Lease to an Application and view any current and past
leases on the application.
I'll have more to write later on how this is going to work in terms of
project process, but basically, each application that we are running in
production gets a lease period (6 months, a year, 2 years, something
like that). At the end of that period, the dev(s), LD/PM, client, and
senior management have an opportunity to check in, establish that the
application is still being used and that the cost of maintaining it is
worth the value that it provides.
UI work to be done later:
* page to show applications with expired and/or soon to expire leases
* calendar/date-picker widget for end-date
* ability to renew a lease before …
=> simple lease UI implemention

requirements.txt
So development for django-storages has switched back from -redux to the
original package name.
This is noted in the new changelog here:
https://github.com/jschneier/django-storages/blob/master/CHANGELOG.rst#14-2016-02-07
Because of that, we've missed the changes in the past year:
https://github.com/jschneier/django-storages/blob/master/CHANGELOG.rst#152-2017-01-13
=> :arrow_up: django-storages 1.5.2

plexus/main/tests/test_views.py, plexus/main/views.py, plexus/templates/base.html, plexus/templates/main/renewals_dashboard.html, plexus/urls.py
(formerly and still elsewhere called 'Leases'. mgmnt decided that that
sounds too legalese, so we're going with 'renewals' from here out)
shows active renewals and shows applications that don't currently have
an active renewal.
=> simple dashboard for renewals

plexus/main/views.py
even if the renewal is still technically valid, there's no point in
listing a deprecated application
=> exclude deprecated applications from renewals

plexus/templates/main/application_detail.html
no point in showing a bunch of "No Data" graphs for an application that
doesn't have the `graphite_name` set.
=> hide graphs if application doesn't have a graphite_name

plexus/settings_shared.py
forgot this little bit of config. Needed to properly pick up different
`BROKER_URL` settings in staging/prod environments.
=> djcelery.setup_loader()

plexus/main/admin.py
Servers should be added through the Add Server form, not the django admin. I'm removing Server
from the admin for now because I don't think it's necessary.
=> Remove Server from admin

Makefile, django.mk, media/js/makegraphs.js
js.mk now includes the eslint command. Removing the eslint definition in the outer Makefile to resolve these warnings:
```
Makefile:19: warning: overriding commands for target `eslint'
js.mk:28: warning: ignoring old commands for target `eslint'
```
Also, `eslint` was not actually running. Adding the command django.mk file and correcting resulting errors.
=> Resolve eslint warning

.bandit, .gitignore, django.mk, requirements.txt
[From the Bandit site](https://github.com/openstack/bandit)...
Bandit is a tool designed to find common security issues in Python code. To do this Bandit processes each file, builds an AST from it, and runs appropriate plugins against the AST nodes. Once Bandit has finished scanning all the files it generates a report.
This PR integrates Bandit into our process. Security warnings will fail the build during the Travis.CI run. Likely, there will be a period of tuning to ensure are running the correct set of tests against our code. Bandit's usefulness is somewhat limited for us, as it cannot scan/lint the underlying Django framework.
=> Bandit integration

plexus/main/views.py, plexus/templates/main/index.html
Some Hugo & Go applications are proxied through our managed servers, but do not have a visible application server of their own. Surface these applications to ensure everything is visible.
=> Surface proxy-only applications

requirements.txt
We deploy on python 2.7.6, which can throw an InsecurePlatformWarning:
https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
The solution is to install `urllib3[secure]`, which requires a few
dependencies including cryptography.
https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2
Also, I've removed a duplicate urllib3 in requirements.txt.
=> Add cryptography

plexus/settings_shared.py, requirements.txt
Based on these instructions:
https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2
This required a few more dependencies as well.
=> Tell urllib3 to use pyOpenSSL

.travis.yml
as discussed on slack, we can tell travis to just use 2.7.6, like our jenkins and prod servers are currently at.
Testing multiple versions will slow down our travis builds but, we'll just see how this behaves.
=> travis: test specifically on python 2.7.6

plexus/grainlog/tests/test_views.py, plexus/grainlog/views.py
This unittest wasn't properly catching this python 3 error, so I've fixed that as well.
=> Fix unicode grainlog encoding error

plexus/grainlog/views.py
Something about concatenating f.chunk() is causing the payload to be empty. Just use f.read().
=> Another grain payload fix

requirements.txt
This was pinned because of dropping python 2 support, and can be unpinned now.
=> :arrow_up: pylint 2.3.1

plexus/settings_shared.py
plexus is now on python3, and no longer needs this.
=> Remove unnecessary urllib3 SSL fix

plexus/main/models.py
This causes the IP addresses to be sorted in the Django admin's form for
the Alias model.
=> IPAddress model: order by IP address

plexus/grainlog/views.py
Trust smart_text() to handle this correctly. Needed for Django 2.2
upgrade.
encoded_payload is still needed for making the sha1 hash.
=> Don't encode payload to bytes before creating GrainLog

requirements.txt
To fix error found on jenkins:
```
from flake8._compat import lru_cache
File "/mnt/jenkins/jobs/plexus/workspace/ve/lib/python3.6/site-packages/flake8/_compat.py", line 12, in <module>
import importlib_metadata
ModuleNotFoundError: No module named 'importlib_metadata'
```
=> Add missing deps for new flake8

requirements.txt
Queues were removed a while ago. Now removing the related libraries.
=> Remove celery dependencies

plexus/templates/main/index.html
btn-default doesn't do anything in newer versions of Bootstrap
=> Change btn-default to btn-primary

plexus/settings_production.py, plexus/settings_staging.py
The new default for this is 'ctl', in ctlsettings: https://github.com/ccnmtl/ctlsettings/blob/main/ctlsettings/staging.py#L11
But, the plexus bucket names, and for most our apps, are still prefixed with "ccnmtl". So, just declare this manually as needed.
=> Use ccnmtl s3prefix

plexus/grainlog/apps.py, plexus/main/apps.py
This change fixes deprecation warnings:
```
main.ServerNote: (models.W042) Auto-created primary key used when not
defining a primary key type, by default 'django.db.models.AutoField'.
HINT: Configure the DEFAULT_AUTO_FIELD setting or the
AppConfig.default_auto_field attribute to point to a subclass of
AutoField, e.g. 'django.db.models.BigAutoField'
```
=> Add missing AppConfig stuff

plexus/grainlog/views.py
Python3 text stuff can be confusing - this should address the error.
=> Store payload as string rather than bytestring

.github/workflows/build-and-test.yml
https://github.blog/changelog/2024-05-14-github-hosted-runners-public-beta-of-ubuntu-24-04-is-now-available/
=> github actions: test on ubuntu 24.04
